version: '3.9'

services:
  worker:
    build: .
    working_dir: /Go/src/sensibull/gop/sensibull/worker
    volumes:
      - .:/Go/src/sensibull/gop/sensibull/worker
    environment:
      - REDIS_HOST=my_redis_container
    networks:
        my_network:
          aliases:
            - redis

networks:
  my_network:
    external:
      name: my_network
